### ISSUE TITLE
Error loading state

### ISSUE THREAD

**Issue by ShahanMirza** [mashun4ek/ecs_terraform_workshop#3]
Hi, 
I am following your workshop tutorial and cloned your test repo, when passed argument its generating following error. Can you please help me out ?
![image](https://user-images.githubusercontent.com/34271340/103215967-a9c12080-4936-11eb-95b2-ca017f4b826b.png)

**Comment by andreprawira** [comment]
create a bucket in us-east-1, remember that bucket name, go to main.tf, replace line 9 with the name of your bucket that you just created

**Comment by ShahanMirza** [comment]
Thanks
